"""Live proof that the worked-example fixtures still apply as documented.

`src/kizen_builder/docs/examples.md` shows the object, fields, activity, and
automation fixtures under `tests/fixtures/examples/service_ticket/` as the
thing a reader copies, adjusts, and applies.
`tests/test_examples_doc_matches_fixtures.py` (offline, every commit) proves
the doc never quietly diverges from those files; this module is the other
half — proving the files themselves still apply against a real Kizen
environment, in the doc's own sequence: object -> fields -> activity ->
automation.

Two of the fixtures carry placeholder UUID tokens
(`<service_tickets_object_uuid>`, etc.) that only exist once the object is
created and read back — this test resolves them exactly the way a human
following the doc would, which makes it also the live proof of the doc's own
"where does this UUID come from" explanations.

No dashboard fixture here: this item's dashboard leg is generated by
`dashboards dashlet-config` rather than authored as a spec (see
`examples.md`), and adding real drift coverage for dashboard create/update is
explicitly out of scope for this item (see the work item's Open questions).

Every create registers its deleter with the `scratch` ledger immediately, per
`tests/drift/conftest.py`'s teardown-guaranteed pattern — nothing here is
meant to outlive this test module.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from tests.conftest import load_fixture
from tests.drift.conftest import create_field_on

pytestmark = pytest.mark.drift

FIXTURE_DIR = "examples/service_ticket"


def _load(name: str) -> Any:
    return load_fixture(f"{FIXTURE_DIR}/{name}")


# ---------------------------------------------------------------------------
# Stage 1: object + category, read back
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def example_object(drift_client, scratch) -> dict[str, Any]:
    """object.json's object + category, then a read-back for the derived name.

    Kizen pluralizes the api_name on create — `examples.md`'s first live
    finding. Every fixture downstream hardcodes the pluralized form
    (`service_tickets`), so this fixture asserts that assumption rather than
    silently trusting it: if Kizen's pluralization ever changes, this fails
    here with a clear reason instead of a confusing 404 three stages later.
    """
    from kizen_builder.api import custom_objects as co_api
    from kizen_builder.models.spec import ObjectDef
    from kizen_builder.tools.planners.objects import _build_object_payload

    spec = _load("object.json")
    obj_def = ObjectDef.model_validate(
        {k: v for k, v in spec.items() if k != "categories"}
    )
    payload = _build_object_payload(obj_def)
    created = co_api.create_object(drift_client, payload)
    scratch.track(
        "custom object",
        created["id"],
        lambda: co_api.delete_object(drift_client, created["id"]),
    )
    live = co_api.get_object(drift_client, created["id"])
    api_name = live["name"]

    assert api_name == "service_tickets", (
        f"object.json's api_name 'service_ticket' came back as {api_name!r}, "
        "not the 'service_tickets' every downstream fixture hardcodes "
        "(fields.json's self-relation, automation.json's target_object). "
        "Kizen's pluralization rule apparently changed — examples.md and "
        "these fixtures need to be revisited, not worked around here."
    )

    categories = [
        co_api.create_category(drift_client, created["id"], {"name": cat["name"]})
        for cat in spec["categories"]
    ]
    for cat in categories:
        scratch.track(
            "category",
            cat["id"],
            lambda cid=cat["id"]: co_api.delete_category(
                drift_client, created["id"], cid
            ),
        )

    return {"uuid": created["id"], "api_name": api_name, "categories": categories}


def test_the_object_applies(example_object):
    assert example_object["uuid"]
    assert example_object["categories"][0]["name"] == "Ticket Details"


# ---------------------------------------------------------------------------
# Stage 2: fields, including the self-referencing relationship
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def example_fields(drift_client, scratch, example_object) -> dict[str, dict[str, Any]]:
    """fields.json's four fields, keyed by their server-confirmed api_name."""
    spec = _load("fields.json")
    return {
        created["name"]: created
        for created in (
            create_field_on(drift_client, scratch, example_object, field)
            for field in spec["fields"]
        )
    }


def test_the_fields_apply(example_fields):
    assert set(example_fields) == {
        "priority",
        "ticket_status",
        "scheduled_date",
        "escalation_ticket",
    }


def test_the_self_relationship_field_resolves(example_fields, example_object):
    """The wiring `context_entity_field` (stage 4) depends on: a relationship
    field whose target is the object it already lives on."""
    hop = example_fields["escalation_ticket"]
    assert hop["field_type"] == "relationship"
    assert hop["relation"]["related_object"] == example_object["uuid"]


# ---------------------------------------------------------------------------
# Stage 3: the activity type — the create-then-associate workaround
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def example_activity(drift_client, scratch, example_object, example_fields):
    """activity.json's fields, then the object association.

    `activities create --spec-file` 400s if `selected_object_ids` is sent
    (examples.md's second live finding: there is no create-time equivalent of
    `activities update --object`) — so this mirrors the doc's own working
    sequence: create the type and its fields first, associate second.
    """
    from kizen_builder.api import activities as act_api
    from kizen_builder.models.spec import ActivityDef, ActivityFieldDef
    from kizen_builder.tools.planners.activities import _build_activity_field_payload

    spec = _load("activity.json")
    priority_uuid = example_fields["priority"]["id"]

    act_def = ActivityDef.model_validate({"name": spec["name"]})
    created = act_api.create_activity(drift_client, {"name": act_def.name})
    scratch.track(
        "activity",
        created["id"],
        lambda: act_api.delete_activity(drift_client, created["id"]),
    )

    fields: dict[str, dict[str, Any]] = {}
    for idx, field in enumerate(spec["fields"]):
        field = dict(field)
        if field.get("field_type") == "activity_custom_field":
            field["custom_object_field"] = priority_uuid
        fd = ActivityFieldDef.model_validate(field)
        payload = _build_activity_field_payload(fd, default_order=idx)
        created_field = act_api.create_activity_field(
            drift_client, created["id"], payload
        )
        scratch.track(
            "activity_field",
            created_field["id"],
            lambda fid=created_field["id"]: act_api.delete_activity_field(
                drift_client, created["id"], fid
            ),
        )
        fields[created_field["name"]] = created_field

    act_api.update_activity(
        drift_client,
        created["id"],
        {
            "association_mode": "selected_objects_associated",
            "associated_objects": [{"custom_object": {"id": example_object["uuid"]}}],
        },
    )
    live = act_api.get_activity(drift_client, created["id"])
    return {"uuid": created["id"], "live": live, "fields": fields}


def test_the_activity_type_applies_with_its_fields(example_activity):
    assert set(example_activity["fields"]) >= {"outcome", "priority_snapshot"}


def test_the_activity_is_associated_to_the_object_by_uuid(
    example_activity, example_object
):
    associated = {c["id"] for c in example_activity["live"]["custom_objects"]}
    assert associated == {example_object["uuid"]}


def test_the_activity_custom_field_mirrors_the_priority_field(
    example_activity, example_fields
):
    snapshot = example_activity["fields"]["priority_snapshot"]
    assert snapshot["custom_object_field"]["id"] == example_fields["priority"]["id"]


# ---------------------------------------------------------------------------
# Stage 4: the automation — both UUID placeholders resolved
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def example_automation(
    drift_client, scratch, example_object, example_fields, example_activity
):
    from kizen_builder.api import automations as auto_api
    from kizen_builder.models.spec import AutomationDef
    from kizen_builder.tools.planners.automations import (
        LiveContext,
        _build_automation_payload,
    )

    text = json.dumps(_load("automation.json"))
    text = text.replace(
        "<service_tickets.escalation_ticket_field_uuid>",
        example_fields["escalation_ticket"]["id"],
    )
    text = text.replace("<site_visit_activity_type_uuid>", example_activity["uuid"])
    auto_def = AutomationDef.model_validate(json.loads(text))

    payload = _build_automation_payload(auto_def, LiveContext())
    created = auto_api.create_automation(drift_client, payload)
    scratch.track(
        "automation",
        created["id"],
        lambda: auto_api.delete_automation(drift_client, created["id"]),
    )
    return {
        "sent": payload,
        "live": auto_api.get_automation(drift_client, created["id"]),
        "uuid": created["id"],
    }


def test_the_automation_applies(example_automation):
    sent_steps = {s["type"] for s in example_automation["sent"]["steps"]}
    assert sent_steps == {
        "condition",
        "create_related_entity",
        "code_step",
        "stop_execution",
        "schedule_activity",
        "go_to_automation_step",
    }


def test_create_related_entity_resolved_the_context_entity_field(
    example_automation, example_fields
):
    """The doc's headline finding: `target_object` (the declared spec field)
    is dead; the builder reads `target_custom_object`. This fixture sends
    both — this asserts the one the server actually stored came through."""
    sent = next(
        s
        for s in example_automation["sent"]["steps"]
        if s["type"] == "create_related_entity"
    )["action_create_related_entity"]
    assert sent["target_custom_object"]
    assert sent["context_entity_field"] == example_fields["escalation_ticket"]["id"]


def test_schedule_activity_points_at_the_activity_type_uuid(
    example_automation, example_activity
):
    sent = next(
        s
        for s in example_automation["sent"]["steps"]
        if s["type"] == "schedule_activity"
    )["action_schedule_activity"]
    assert sent["activity_type_id"] == example_activity["uuid"]
